return {
	"romus204/tree-sitter-manager.nvim",
	dependencies = {},
	event = { "BufReadPost", "BufNewFile" },
	config = function()
		require("tree-sitter-manager").setup({
			border = "rounded",
			auto_install = true,
			hightlight = true,
			nerdfont = true,
			ensure_installed = {
				"bash",
				"lua",
				"html",
				"css",
				"typescript",
				"javascript",
				"jsx",
				"tsx",
				"json",
				"toml",
				"yaml",
				"jsdoc",
				"python",
				"rust",
				"markdown",
				"regex",
				"dockerfile",
				"vimdoc",
				"diff",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
			},
		})
	end,
}
