local g = vim.g
g.edge_style = 'neon'
g.edge_better_performance = 1
g.edge_dim_foreground = 0
g.edge_dim_inactive_windows = 1
g.edge_disable_italic_comment = 1
g.edge_transparent_background = 0
g.edge_menu_selection_background = 'blue'
g.edge_disable_terminal_colors = 1
g.edge_show_eob = 0
